version: "3.8"

services:
  readisgood-postgres:
    container_name: readisgood-postgres
    image: "postgres:15.0"
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - readisgood-postgres-volume:/var/lib/postgresql/data

  readisgood-backend:
    container_name: readisgood-backend
    image: readisgood:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      JDBC_URL: "jdbc:postgresql://readisgood-postgres:5432/postgres"
      JDBC_USER_NAME: "postgres"
      JDBC_PASSWORD: "postgres"
    depends_on:
      readisgood-postgres:
        condition: service_healthy
volumes:
  readisgood-postgres-volume: